version: "3.9"

services:
  sample_app:
    image: gradle:jdk11
    container_name: sample_app
    working_dir: /sample_app
    volumes:
      - .:/sample_app
    ports:
      - 8080:8080
    expose:
      - 8080
    command: tail -f docker-compose.yml