#!/bin/bash -x
# script to be run after deployment install

#### variables

base_path="/srv/www/${DEPLOYMENT_GROUP_NAME}"

#### functions

get_vhost()
{
	aws s3 cp "s3://serrfdeploy/${APPLICATION_NAME}/${APPLICATION_NAME}.conf" /etc/apache2/vhosts.d/ || exit $?
}

get_env()
{
	aws s3 cp "s3://serrfdeploy/${APPLICATION_NAME}/.env" "${base_path}/"
}

symlink_storage()
{
	rm -rf "${base_path}/deploy/storage" || exit $?

	ln -s "${base_path}/storage/" "${base_path}/deploy/storage" || $?
}

symlink_env()
{
	ln -s "${base_path}/.env" "${base_path}/deploy/.env" || $?
}

chmod_bootstrap()
{
	chmod -R 0775 "${base_path}/deploy/bootstrap" || $?
	chmod -R 0777 "${base_path}/deploy/bootstrap/cache" || $?
}

install_composer_dependencies()
{
	composer install -d "${base_path}/deploy/" || $?
}


#### main
get_vhost
get_env
symlink_storage
symlink_env
chmod_bootstrap
install_composer_dependencies