#!/bin/bash -x
# script to be run before deployment install

#### variables

site=""
base_path=""
release_path=""



release=$(TZ="America/Los_Angeles" date +"%Y%m%d%H%M%S")


#### functions

set_site()
{
	if [ -z "$DEPLOYMENT_GROUP_NAME" ]
	then
		site="nogroup"
	else
		site=$DEPLOYMENT_GROUP_NAME
	fi
}

set_base_path()
{
	base_path="/srv/www/$site"
}

set_release_path()
{
	release_path="${base_path}/releases/${release}"
}

create_release_directory()
{
	mkdir -p $release_path || exit $?
}

create_storage()
{
	mkdir -p "${base_path}/storage/app/public" || exit $?
	mkdir -p "${base_path}/storage/framework/cache" || exit $?
	mkdir -p "${base_path}/storage/framework/sessions" || exit $?
	mkdir -p "${base_path}/storage/framework/views" || exit $?
	mkdir -p "${base_path}/storage/logs" || exit $?
	chmod -R 0777 "${base_path}/storage" || exit $?

}

symlink_deploy()
{
	if [ -L "${base_path}/deploy" ]
	then
		rm -f "${base_path}/deploy" || exit $?
	fi

	ln -s "$release_path" "${base_path}/deploy" || exit $?
}





#### main

set_site $1
set_base_path
set_release_path
create_release_directory
# create_storage
symlink_deploy